# Generated by Django 2.2 on 2020-09-14 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200914_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='braintree_id',
            new_name='braintreeID',
        ),
    ]
